apiVersion: apps/v1
kind: Deployment
metadata:
  name: kos-mock
  namespace: phonebill-dg0508
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kos-mock
  template:
    metadata:
      labels:
        app: kos-mock
    spec:
      imagePullSecrets:
        - name: phonebill
      containers:
        - name: kos-mock
          image: acrdigitalgarage02.azurecr.io/phonebill/kos-mock:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: cm-common
            - configMapRef:
                name: cm-kos-mock
          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "1024Mi"
              cpu: "1024m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3