apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-product-service
  namespace: phonebill-dg0508
data:
  # Server Configuration
  SERVER_PORT: "8083"
  SPRING_PROFILES_ACTIVE: "dev"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"

  # Database Configuration
  DB_HOST: "product-db-service"
  DB_PORT: "5432"
  DB_KIND: "postgresql"
  DB_NAME: "product_change_db"
  DB_USERNAME: "product_change_user"
  DDL_AUTO: "update"

  # Redis Configuration
  REDIS_HOST: "20.249.193.103"
  REDIS_PORT: "6379"
  REDIS_DATABASE: "2"

  # KOS API Configuration
  KOS_BASE_URL: "http://kos-mock:80"
  KOS_CLIENT_ID: "product-service-dev"
  KOS_MOCK_ENABLED: "true"

  # JWT Configuration
  JWT_ACCESS_TOKEN_VALIDITY: "18000000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"