apiVersion: v1
kind: Secret
metadata:
  name: secret-product-service
  namespace: phonebill-dg0508
type: Opaque
stringData:
  # Database Password
  DB_PASSWORD: "ProductUser2025!"

  # Redis Password
  REDIS_PASSWORD: "Redis2025Dev!"

  # JWT Secret
  JWT_SECRET: "nwe5Yo9qaJ6FBD/Thl2/j6/SFAfNwUorAY1ZcWO2KI7uA4bmVLOCPxE9hYuUpRCOkgV2UF2DdHXtqHi3+BU/ecbz2zpHyf/720h48UbA3XOMYOX1sdM+dQ=="

  # KOS API Key
  KOS_API_KEY: "dev-api-key"