apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: phonebill-dg0508
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 80
      targetPort: 8083
      protocol: TCP
  type: ClusterIP